config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#landing'
  get 'pages/landing'
  get 'pages/new_game'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def landing
    render "application/hello_world"
  end
  def new_game
    render "application/new_game"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/hello_world.html.erb
<h1>Hiya</h1>
<%= link_to "New Game", pages_new_game_path %>

app/views/application/new_game.html.erb
<h1>Hiya</h1>
<%= link_to "New Game", pages_new_game_path %>
<p>player 1 cards</p>
<p>player 2 cards</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>